#!/bin/bash
DEFAULT_APP_NAME='MyApp'

if [ -z ${1+$DEFAULT_APP_NAME} ]; then 
    APP_NAME=$DEFAULT_APP_NAME
    echo "No app name given, defaulting to '$DEFAULT_APP_NAME'"
    echo "To fix this, please specify an app name with the following syntax:"
    echo -e "\t./init <appName>"
else
    APP_NAME=$1
fi

mkdir src/$APP_NAME
CLASS_FILE="src/$APP_NAME/$APP_NAME.ts"
touch $CLASS_FILE
chmod +rw $CLASS_FILE
read -r -d '' TEMPLATE << EOF
namespace $APP_NAME {
    export class $APP_NAME extends Canvity.App {
        public constructor(canvas: HTMLCanvasElement) {
            super(canvas);
        }

        public PreInit(opts: any): void {
            // TODO: Add PreInit logic
        }

        public Init(drawDeltaTime: number, updateDeltaTime: number): void {
            // TODO: Add Init logic
        }

        public PostInit(): void {
            // TODO: Add PostInit logic
        }
    }
}
EOF
echo "$TEMPLATE" > $CLASS_FILE

RUN_FILE="src/$APP_NAME/Run$APP_NAME.ts"
read -r -d '' TEMPLATE << EOF
window.addEventListener('load', function(ev: Event) {
    let canvas: HTMLElement | null = document.getElementById('canvity-canvas');
    if (canvas === null) {
        console.error("Could not find canvas element with id 'canvity-canvas'!");
        return;
    }
    if (!(canvas instanceof HTMLCanvasElement)) {
        console.error("Element with id 'canvity-canvas' is not a HTML Canvas!");
        return;
    }
    
    let app: Canvity.App = new $APP_NAME.$APP_NAME(canvas);
    Canvity.StartApp(app);
});
EOF
echo "$TEMPLATE" > $RUN_FILE